sonar.organization=hothihuuphi
sonar.projectKey=aiops-rca
sonar.projectName=aiops-rca
sonar.sourceEncoding=UTF-8
sonar.sources=aiops_framework,pipeline,tools
sonar.tests=tests
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.ipynb,artifacts/**,data_anomaly_balanced_v3/**,data_rca_balanced_v3/**,src/**,release/**,kustomize/**,terraform/**,observability/**
sonar.test.inclusions=tests/**/*.py

