apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/huymt05/aiops-rca.git
    targetRevision: main
    path: deploy/mlops/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
